### ISSUE TITLE
Issue on docs

### ISSUE THREAD

**Issue by Binapps** [OpenPipe/openpipe#219] opened 2023-09-11 20:27 UTC
Path: /overview
Quisiera saber si puedo entrenar un modelo con la interacción del cliente, runcionario_de_soporte, y con las preguntas del cliente y las respuestas del usuario, ir entrenando el modelo personalizado en llama2, por ejemplo?

**Comment by arcticfly** [comment] 2023-09-12 20:28
Hey Binapps. Yes, training a small model on interactions between support staff and customers is possible, but may not always be advisable. If the staff have a wide range of possible answers and need to deal with many unrelated requests, then a small model will have trouble internalizing all the lessons it needs to learn from a large model in order to properly handle incoming requests. However, if the tasks you want your fine-tuned model to do are narrowly scoped, e.g. fulfill account update requests, triage incoming emails, etc, then a fine-tuned model could do just fine. Does that answer your question?

**Comment by arcticfly** [comment] 2023-09-12 21:11
Closing as duplicate of #220

**Closed as completed by arcticfly** 2023-09-12 21:11 UTC
